// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAA_8UaJBxYgO4-BYYqILejA9U8dHJRnE',
    appId: '1:337030802639:web:1b6ec1103180c11c3e5bba',
    messagingSenderId: '337030802639',
    projectId: 'bobscapes-fd33a',
    authDomain: 'bobscapes-fd33a.firebaseapp.com',
    storageBucket: 'bobscapes-fd33a.appspot.com',
    measurementId: 'G-3NYXRJJ4C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoM9xuMxiAHACX2abOwjmVdjGnw1_99YM',
    appId: '1:337030802639:android:cdf8bf7d958e86403e5bba',
    messagingSenderId: '337030802639',
    projectId: 'bobscapes-fd33a',
    storageBucket: 'bobscapes-fd33a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0nt8VuNErc3vPNR6Bv5e3f4xXoeigcTI',
    appId: '1:337030802639:ios:78eadbb89c95f0473e5bba',
    messagingSenderId: '337030802639',
    projectId: 'bobscapes-fd33a',
    storageBucket: 'bobscapes-fd33a.appspot.com',
    iosClientId: '337030802639-0tjtv38meb562hpfm1orse6iv6cdp2ai.apps.googleusercontent.com',
    iosBundleId: 'com.fergusonlynchllc.bobscapes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0nt8VuNErc3vPNR6Bv5e3f4xXoeigcTI',
    appId: '1:337030802639:ios:78eadbb89c95f0473e5bba',
    messagingSenderId: '337030802639',
    projectId: 'bobscapes-fd33a',
    storageBucket: 'bobscapes-fd33a.appspot.com',
    iosClientId: '337030802639-0tjtv38meb562hpfm1orse6iv6cdp2ai.apps.googleusercontent.com',
    iosBundleId: 'com.fergusonlynchllc.bobscapes',
  );
}
